# unrecoverable-panic

```shell
$ go run main.go 
panic: something went wrong

goroutine 17 [running]:
main.f.func1()
        /workspaces/unrecoverable-panic/main.go:16 +0x2a
created by main.f
        /workspaces/unrecoverable-panic/main.go:16 +0x4a
exit status 2
$
```